/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface JobManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptJob"
      | "approveAndPay"
      | "convertUsdToEth"
      | "getLatestPrice"
      | "i_priceFeed"
      | "postJob"
      | "s_jobCounter"
      | "s_jobs"
      | "submitResult"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "JobAccepted"
      | "JobApproved"
      | "JobPosted"
      | "JobResultSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveAndPay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertUsdToEth",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "i_priceFeed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "postJob",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "s_jobCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_jobs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResult",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "acceptJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveAndPay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertUsdToEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "i_priceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "postJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "s_jobCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "s_jobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitResult",
    data: BytesLike
  ): Result;
}

export namespace JobAcceptedEvent {
  export type InputTuple = [jobId: BigNumberish, provider: AddressLike];
  export type OutputTuple = [jobId: bigint, provider: string];
  export interface OutputObject {
    jobId: bigint;
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobApprovedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    requester: AddressLike,
    provider: AddressLike,
    rewardEth: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    requester: string,
    provider: string,
    rewardEth: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    requester: string;
    provider: string;
    rewardEth: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobPostedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    requester: AddressLike,
    rewardUsd: BigNumberish,
    rewardEth: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    requester: string,
    rewardUsd: bigint,
    rewardEth: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    requester: string;
    rewardUsd: bigint;
    rewardEth: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobResultSubmittedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    provider: AddressLike,
    resultUrl: string
  ];
  export type OutputTuple = [
    jobId: bigint,
    provider: string,
    resultUrl: string
  ];
  export interface OutputObject {
    jobId: bigint;
    provider: string;
    resultUrl: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface JobManager extends BaseContract {
  connect(runner?: ContractRunner | null): JobManager;
  waitForDeployment(): Promise<this>;

  interface: JobManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  approveAndPay: TypedContractMethod<
    [jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  convertUsdToEth: TypedContractMethod<
    [usdAmount: BigNumberish],
    [bigint],
    "view"
  >;

  getLatestPrice: TypedContractMethod<[], [bigint], "view">;

  i_priceFeed: TypedContractMethod<[], [string], "view">;

  postJob: TypedContractMethod<
    [dataUrl: string, rewardUsd: BigNumberish],
    [void],
    "payable"
  >;

  s_jobCounter: TypedContractMethod<[], [bigint], "view">;

  s_jobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, bigint, bigint] & {
        requester: string;
        provider: string;
        dataUrl: string;
        resultUrl: string;
        rewardUsd: bigint;
        rewardEth: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  submitResult: TypedContractMethod<
    [jobId: BigNumberish, resultUrl: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveAndPay"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "convertUsdToEth"
  ): TypedContractMethod<[usdAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLatestPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "i_priceFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "postJob"
  ): TypedContractMethod<
    [dataUrl: string, rewardUsd: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "s_jobCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_jobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, bigint, bigint] & {
        requester: string;
        provider: string;
        dataUrl: string;
        resultUrl: string;
        rewardUsd: bigint;
        rewardEth: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitResult"
  ): TypedContractMethod<
    [jobId: BigNumberish, resultUrl: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "JobAccepted"
  ): TypedContractEvent<
    JobAcceptedEvent.InputTuple,
    JobAcceptedEvent.OutputTuple,
    JobAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "JobApproved"
  ): TypedContractEvent<
    JobApprovedEvent.InputTuple,
    JobApprovedEvent.OutputTuple,
    JobApprovedEvent.OutputObject
  >;
  getEvent(
    key: "JobPosted"
  ): TypedContractEvent<
    JobPostedEvent.InputTuple,
    JobPostedEvent.OutputTuple,
    JobPostedEvent.OutputObject
  >;
  getEvent(
    key: "JobResultSubmitted"
  ): TypedContractEvent<
    JobResultSubmittedEvent.InputTuple,
    JobResultSubmittedEvent.OutputTuple,
    JobResultSubmittedEvent.OutputObject
  >;

  filters: {
    "JobAccepted(uint256,address)": TypedContractEvent<
      JobAcceptedEvent.InputTuple,
      JobAcceptedEvent.OutputTuple,
      JobAcceptedEvent.OutputObject
    >;
    JobAccepted: TypedContractEvent<
      JobAcceptedEvent.InputTuple,
      JobAcceptedEvent.OutputTuple,
      JobAcceptedEvent.OutputObject
    >;

    "JobApproved(uint256,address,address,uint256)": TypedContractEvent<
      JobApprovedEvent.InputTuple,
      JobApprovedEvent.OutputTuple,
      JobApprovedEvent.OutputObject
    >;
    JobApproved: TypedContractEvent<
      JobApprovedEvent.InputTuple,
      JobApprovedEvent.OutputTuple,
      JobApprovedEvent.OutputObject
    >;

    "JobPosted(uint256,address,uint256,uint256)": TypedContractEvent<
      JobPostedEvent.InputTuple,
      JobPostedEvent.OutputTuple,
      JobPostedEvent.OutputObject
    >;
    JobPosted: TypedContractEvent<
      JobPostedEvent.InputTuple,
      JobPostedEvent.OutputTuple,
      JobPostedEvent.OutputObject
    >;

    "JobResultSubmitted(uint256,address,string)": TypedContractEvent<
      JobResultSubmittedEvent.InputTuple,
      JobResultSubmittedEvent.OutputTuple,
      JobResultSubmittedEvent.OutputObject
    >;
    JobResultSubmitted: TypedContractEvent<
      JobResultSubmittedEvent.InputTuple,
      JobResultSubmittedEvent.OutputTuple,
      JobResultSubmittedEvent.OutputObject
    >;
  };
}
