name: Build executável com PyInstaller

on:
  push:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    # Executa o job em paralelo para cada plataforma na matriz
    runs-on: ${{ matrix.os }}

    # A "matriz de estratégia" define as combinações de SO e Python
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10'] # Especifique a versão do Python que você usa

    steps:
      # Etapa 1: Faz o checkout do seu código no repositório
      - name: 'Checkout code'
        uses: actions/checkout@v4

      # Etapa 2: Configura o ambiente Python
      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      # Etapa 3: Instala as dependências
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # Se você tiver um arquivo requirements.txt:
          # pip install -r requirements.txt

      # Etapa 4: Define nomes de arquivos e caminhos específicos da plataforma
      - name: 'Set platform-specific names'
        shell: bash
        run: |
          SCRIPT_PATH="desktop/worker_app.py"
          SCRIPT_FILENAME=$(basename $SCRIPT_PATH)
          APP_NAME=$(echo $SCRIPT_FILENAME | cut -f 1 -d '.')
          
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "EXECUTABLE_NAME=${APP_NAME}.exe" >> $GITHUB_ENV
            echo "ZIP_NAME=${APP_NAME}-windows.zip" >> $GITHUB_ENV
          elif [ "$RUNNER_OS" == "macOS" ]; then
            echo "EXECUTABLE_NAME=${APP_NAME}" >> $GITHUB_ENV
            echo "ZIP_NAME=${APP_NAME}-macos.zip" >> $GITHUB_ENV
          else
            echo "EXECUTABLE_NAME=${APP_NAME}" >> $GITHUB_ENV
            echo "ZIP_NAME=${APP_NAME}-linux.zip" >> $GITHUB_ENV
          fi
          
          echo "SCRIPT_PATH=${SCRIPT_PATH}" >> $GITHUB_ENV

      # Etapa 5: Executa o PyInstaller
      - name: 'Run PyInstaller'
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            pyinstaller --onefile --windowed --name="${{ env.EXECUTABLE_NAME }}" ${{ env.SCRIPT_PATH }}
          else
            pyinstaller --onefile --noconsole --name="${{ env.EXECUTABLE_NAME }}" ${{ env.SCRIPT_PATH }}
          fi

      # Etapa 6: Compacta o executável
      - name: 'Zip the executable (Windows)'
        if: runner.os == 'Windows'
        run: Compress-Archive -Path dist/${{ env.EXECUTABLE_NAME }} -DestinationPath ${{ env.ZIP_NAME }}

      - name: 'Zip the executable (Linux/macOS)'
        if: runner.os != 'Windows'
        run: zip ${{ env.ZIP_NAME }} dist/${{ env.EXECUTABLE_NAME }}

      # Etapa 7: Upload na release (produção)
      - name: 'Upload artifact to Release (Production)'
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.ZIP_NAME }}
          asset_name: ${{ env.ZIP_NAME }}
          asset_content_type: application/zip

      # Etapa 8: Upload de artefato para testes
      - name: 'Upload artifact for testing (Development)'
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: ./${{ env.ZIP_NAME }}
